### ISSUE TITLE
!!Plug.Conn.get_session(conn, :current_user_id)

### ISSUE THREAD

**Issue by niccolox** [elixircastsio/042-user-authentication#1]
can you explain the !!

https://github.com/elixircastsio/042-user-authentication/blob/master/lib/teacher_web/helpers/auth.ex

is this a double negative?

if so, why not just use a positive?

**Comment by alkx** [comment]
Yeah, it's basically a double negative. The `!` is nice because it casts any value to its boolean representation. But it could be better for readability.

We could write a function that would be more readable. Maybe something like: 
`exists?(current_user_id)` 

I'm open to any ideas/suggestions on refactoring this.

**Comment by niccolox** [comment]
I am interested to see what the new canonical Phx 1.4 book prescribes

there is a wide range of implementation styles, which is fine, but some leadership on simple and advanced implementations would be grand

**Comment by niccolox** [comment]
btw, I used a mix of 
https://github.com/Diamond/pxblog/blob/master/web/controllers/user_controller.ex

and 
https://github.com/terakilobyte/rumbl/blob/master/web/controllers/auth.ex
